import pygame

SCREEN=pygame.display.set_mode()
WIDTH=SCREEN.get_width()
HEIGHT=SCREEN.get_height()

FPS=60

DOG_NORMAL_VELOCITY = 5
DOG_BOOST_VELOCITY = 10
PLAYER_STARTING_BOOSTLEVEL = 100
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600


BURGER_STARTING_VELOCITY = 4

BOMB_STARTING_VELOCITY=4

CLOCK = pygame.time.Clock()
